export const SliderSettings ={
    slidesPerView:3,
    spaceBetween:40,
    breakpoints:{
        200:{
            slidesPerView:1
        },
        480:{
            slidesPerView:2
        },
        600:{
            slidesPerView:2
        },
        750:{
            slidesPerView:3
        },
        1100:{
            slidesPerView:3
        }
    }
}